services:


  # todolist-app:
  #   container_name: todolist-app
  #   #build: .
  #   image: todolist-app:0.0.0
  #   ports:
  #     - "3000:3000"
  #   env_file: .env
  #   networks:
  #     - todolist-network
  
  postgres15:
    container_name: postgres15
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Atlantic/Cape_Verde"
    volumes:
      - pg15_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - network-postgres
      - todolist-network
    
  

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:9.2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-2025:/var/lib/pgadmin
    networks:
      - network-postgres
      - todolist-network

volumes:
  pg15_data:
    name: pg15_data
  pgadmin-2025:
    name: pgadmin-2025

networks:
  network-postgres:
    name: network-postgres
  todolist-network:
    name: todolist-network
    external: true
      