services:
  postgres15:
    container_name: postgres15
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Atlantic/Cape_Verde"
    volumes:
      - pg15_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - network-postgres

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:9.2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-2025:/var/lib/pgadmin
    networks:
      - network-postgres

volumes:
  pg15_data:
    name: pg15_data

  pgadmin-2025:
    name: pgadmin-2025

networks:
  network-postgres: